<?php 
if ( 'POST' != $_SERVER['REQUEST_METHOD'] ) {
	header('Allow: POST');
	header('HTTP/1.1 405 Method Not Allowed');
	header('Content-Type: text/plain');
	exit;
}

require_once("wp-load.php");

if ( ! function_exists( 'wp_handle_upload' ) ) {
    require_once( ABSPATH . 'wp-admin/includes/file.php' );
}

nocache_headers();


$user_ID = get_current_user_id(); 
echo '<pre>';
print_r($_POST['low_power']);
echo '</pre>';

$uploadedfile = $_FILES['file'];

$upload_overrides = array( 'test_form' => false );

$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

if ( $movefile && !isset( $movefile['error'] ) ) {
    update_user_meta($user_ID,'avatar_user',$movefile['url']);
} else {
    /**
     * Error generated by _wp_handle_upload()
     * @see _wp_handle_upload() in wp-admin/includes/file.php
     */
    echo $movefile['error'];
}


wp_update_user( array( 'ID' => $user_ID, 'display_name' => $_POST['username'] ) );
update_user_meta($user_ID, 'name_change_counter',1);
update_user_meta($user_ID,'phone_number',$_POST['phonenumber']);

update_user_meta($user_ID, 'low_power',$_POST['low_power']);
update_user_meta($user_ID, 'low_buildings',$_POST['buildings']);

update_user_meta($user_ID,'user_country',$_POST['countrycode']);

$_SESSION['status'] = '3212';wp_redirect(get_permalink(6570)); exit;