<?php
if ('POST' != $_SERVER['REQUEST_METHOD']) {
    header('Allow: POST');
    header('HTTP/1.1 405 Method Not Allowed');
    header('Content-Type: text/plain');
    exit;
}

require_once("wp-load.php");

if (! function_exists('wp_handle_upload')) {
    require_once(ABSPATH . 'wp-admin/includes/file.php');
}

nocache_headers();


$user_ID = get_current_user_id();


$uploadedfile = $_FILES['file'];

if(isset($_FILES['file'])) {
    if($_FILES['file']['size'] > 150000) { //200 KB (size is also in bytes)
	    
	    $_SESSION['status'] = 'Maximum file size is 150KB';
	    wp_redirect(get_permalink(6570));
	    exit;

    }}

$upload_overrides = array( 'test_form' => false );

$movefile = wp_handle_upload($uploadedfile, $upload_overrides);

if ($movefile && !isset($movefile['error'])) {
    update_user_meta($user_ID, 'avatar_user', $movefile['url']);
} else {
    /**
     * Error generated by _wp_handle_upload()
     * @see _wp_handle_upload() in wp-admin/includes/file.php
     */
    echo $movefile['error'];
}

if (!empty($_POST['username'])) {
    if (get_user_meta($user_ID, 'name_change_counter', true) != 1) {
        $args= array(
        'search' => $_POST['username'], // or login or nicename in this example
        'search_fields' => array('user_login','user_nicename','display_name')
            );
    
            $user = new WP_User_Query($args);
    
            $users = count($user->results);
    
        if ($user->results[0]->data->ID != $user_ID) {
            if ($users >= 1) {
                $_SESSION['status'] = 'Username already exists';
                wp_redirect(get_permalink(6570));
                exit;
            }
        }

        if (strtolower($_POST['username']) != strtolower($user->results[0]->data->display_name)) {
                wp_update_user(array( 'ID' => $user_ID, 'display_name' => $_POST['username'] ));
                update_user_meta($user_ID, 'name_change_counter', 1);
        }
    }
} // end check for name change counter

update_user_meta($user_ID, 'phone_number', $_POST['phonenumber']);
update_user_meta($user_ID, 'desktop_view', $_POST['desktopview']);

update_user_meta($user_ID, 'low_power', $_POST['low_power']);
update_user_meta($user_ID, 'low_buildings', $_POST['buildings']);

update_user_meta($user_ID, 'user_country', $_POST['countrycode']);

$_SESSION['status'] = 'Profile updated';
wp_redirect(get_permalink(6570));
exit;
