<?php
		$weather = array(
	'rainy' 		=> array(
			'name'			=>	'Rainy',
			'icon'			=>	'wi-rain-mix',
			'effect'		=>	'Attack power of vehicles and infantry reduced by 10%.'),
	'snow' 		=> array(
			'name'			=>	'Snow',
			'effect'		=>	'Attack power of vehicles and infantry increased by 10%.'),
	'sandstorms' => array(
			'name'			=>	'Sand-Storms',
			'effect'		=>	'Defense of vehicles and infantry reduced by 10%.'),
	'stormy' 	=> array(
			'name'			=>	'Stormy',
			'effect'		=>	'Attack power of sea units and air units reduced by 10%.'),
	'sunny' 		=> array(
			'name'			=>	'Sunny',
			'effect'		=>	'Attack power of sea units and air units increased by 10%.'),
	'snowstorms' 	=> array(
			'name'			=>	'Snow-Storms',
			'effect'		=>	'Defense of sea units and air units reduced by 10%.'),
	'cloudy' 		=> array(
			'name'			=>	'Cloudy',
			'effect'		=>	'Just a few clouds. No units or buildings impacted.'),
	'foggy' 		=> array(
			'name'			=>	'Foggy',
			'effect'		=>	'Defense of buildings increased by 15%.'),
	'mist' 		=> array(
			'name'			=>	'Mist',
			'effect'		=>	'Attack power of defense buildings reduced by 10%.'),
	'thunderstorm' 	=> array(
			'name'			=>	'Thunderstorm',
			'effect'		=>	'Power production of powerplants recuded by 10%.'),);